install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
    - gcc-5
    - g++-5
    - clang-3.7
os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
script:
  - mkdir build
  - cd build
  - cmake .. && make
notifications:
  email: false
sudo: false